### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Trim21** [bangumi/dev-docs#1]
## Stage 1 只读API

Wiki:

- [X] 现实人物API https://github.com/bangumi/server/pull/3
- [ ] 虚拟角色API https://github.com/bangumi/server/issues/16
- [ ] 条目相关API https://github.com/bangumi/server/issues/18

社区相关API:

- [ ] 小组
- [ ] 条目讨论/小组讨论
- [ ] Timeline

## Stage 2 用户权限认证

- [ ] 用户鉴权API

## Stage 3 读写API

- [ ] 用户个人状态AP
  - [ ] 条目收藏
  - [ ] 观看进度更新
  - [ ] 人物收藏
  - [ ] 角色收藏
  - [ ] 讨论贴收藏（目前无此功能）
- [ ] 发帖，回复
- [ ] 发表timeline

### Wiki 相关api

- [ ] 条目编辑
- [ ] 章节编辑
- [ ] 人物编辑
- [ ] 虚拟角色编辑
- [ ] 条目关联
- [ ] 人物关联
- [ ] 虚拟角色关联

- 用户相关 Wiki User API，如收藏、收视进度、Timeline
- 社区相关 Community API

# 其他

- [ ] 完善wiki语法的spec [wiki-syntax-spec](https://github.com/bangumi/wiki-syntax-spec)
